### ISSUE TITLE
"Generic" test enhancement request

### ISSUE THREAD

**Issue by blipntime** [emberjs/ember-mocha#103]
We want to be able to test "anything". For example we want to test helpers and still access the "render" method. Does this question make sense?
Is there a way to configure setupTest so I can test a helper without having to use a component with an (almost) blank template? If not, can you please make setupTest generic or advise.

**Comment by blipntime** [comment]
Update: using the new API ("describe"), I want to write a generic test like this:

```
import { describe, it } from 'mocha';
import { setupComponentTest } from 'ember-mocha';

describe('MyTestXXX', function() {
  setupComponentTest('', {
    // specify the other units that are required for this test
    // needs: ['component:foo', 'helper:bar']
  });

  it('renders', function() {
    expect(this.render).to.be.ok;
  });
});
```

Where do I place this file and how do I name it? If I just save it as my-test.js into tests, I get:
MyTestXXX
"before each" hook for "renders" ‣
TypeError: Invalid Fullname, expected: 'type:name' got: component:
    at Registry.validateFullName (http://localhost:7357/assets/vendor.js:17230:15)

"after each" hook for "renders" ‣
TypeError: Cannot read property 'subject' of undefined
    at Klass.teardownSubject (http://localhost:7357/assets/test-support.js:23378:31)

Please advise.

**Comment by Turbo87** [comment]
@blipntime why don't you use `ember generate helper-test foo`?

in your example you're passing an empty string to `setupComponentTest()` which can't work.

**Comment by blipntime** [comment]
Thanks!
