### ISSUE TITLE
setupTest is undefined

### ISSUE THREAD

**Issue by allthesignals** [emberjs/ember-mocha#112]
`import { setupTest } from 'ember-mocha';`

setupTest is undefined (when used, undefined is not a function). 

relevant package/bower json:
```
   "ember": "~2.9.0",
    "ember-cli-mocha": "0.11.0",
    "ember-mocha": "0.9.3",
```

Any thoughts? I'm just trying to setup a controller to test a mixin...

**Comment by Turbo87** [comment]
`ember-cli-mocha@0.11.0` has a dependency on `ember-mocha@^0.8.11`, which means that it is only compatible with 0.8.x, and `setupTest` was introduced in v0.9.0.

`ember-cli-mocha@0.12.0` however depends on v0.9.x, so you should be able to use the new syntax once you update your `ember-cli-mocha` version.
