### ISSUE TITLE
RFC: Drop "ember-mocha-adapter" in favor of a wrapper function

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-mocha#115]
We are currently using [`ember-mocha-adapter`](https://github.com/teddyzeenny/ember-mocha-adapter) to implement async acceptance tests using the built-in async Ember helpers, without using `done()` or returning a `Promise`. The `ember-mocha-adapter` is implementing this by overriding the `it()` function and patching in our custom async handling. This is however error-prone and brittle as demonstrated by e.g. https://github.com/ember-cli/ember-cli-mocha/issues/73 which shows that this approach will no longer work with Mocha 3.x.

A potential solution to this is using a wrapper function like this:

```js
it('acceptance test works', emberAsync(function() {
  visit('/');
  andThen(function() {
    expect(currentURL()).to.equal('/foobar');
  });
}));
```

The `emberAsync()` function will call the passed in function and return a `Promise` waiting for any async behavior that was triggered inside the passed in function, e.g. by `return wait()` or `return andThen(function() {})` if `wait()` is not yet available in Ember.

My [initial spike](https://github.com/Turbo87/__mocha-spike__/commit/2980522b5e78e09be5951725d79e84db1752d5bc) used the function name `async()` instead of `emberAsync()`, but @rwjblue correctly pointed out that this will lead to naming conflicts with the upcoming async/await feature and we should try to avoid that. I'd be happy to hear other naming suggestions though.

see also https://github.com/teddyzeenny/ember-mocha-adapter/issues/35#issuecomment-259979473

/cc @rwjblue @trentmwillis @teddyzeenny @dgeb

**Comment by dwickern** [comment]
I use `done()` in my tests and I wasn't aware of this feature. I'd rather opt into this functionality as opposed to changing the behavior of mocha.

How is this better than async/await, which should work fine today (provided the necessary polyfills)?
```
it('acceptance test works', async function() {
  await visit('/');
  await andThen(function() {
    expect(currentURL()).to.equal('/foobar');
  });
});
```

**Comment by Turbo87** [comment]
@dwickern it is *not* better than async/await, but async/await isn't that widely available and simply not the default recommendation yet.

In fact your example could probably even be simplified to this:

```js
it('acceptance test works', async function() {
  await visit('/');
  expect(currentURL()).to.equal('/foobar');
});
```

in other words: `andThen()` will no longer be necessary if async helpers as used with `await`.

> I'd rather opt into this functionality as opposed to changing the behavior of mocha.

that is precisely what I am proposing :)

**Comment by rwjblue** [comment]
This seems good to me, however it will require another round of blueprint updates based on version (which will be annoying) 😝

**Comment by Turbo87** [comment]
@rwjblue I know, but this will only require an update to the `acceptance-test` blueprint, so it's not *that* bad :)

**Comment by Turbo87** [comment]
maybe we should use the name `usingAsyncHelpers(...)` instead of `emberAsync(...)` to make the intent a bit clearer

**Comment by Turbo87** [comment]
see https://github.com/emberjs/ember-mocha/pull/116#issuecomment-265983396
