### ISSUE TITLE
why does the resolver try to import itself?

### ISSUE THREAD

**Issue by marclundgren** [emberjs/ember-mocha#127]
I'm [following the docs for defining a resolver](https://github.com/emberjs/ember-mocha#setting-the-resolver). Why does the code for the resolver try to import itself, but at the wrong path?

```
not ok 1 PhantomJS 2.1 - Global error: Error: Could not find module `app/tests/helpers/helpers/resolver` imported from `app/tests/helpers/resolver` at http://localhost:7357/assets/vendor.js, line 248
```

```
// app/tests/helpers/resolver.js

import resolver from './helpers/resolver';
import { setResolver } from 'ember-mocha';

setResolver(resolver);
```

**Comment by Turbo87** [comment]
as you can see in https://github.com/ember-cli/ember-cli-mocha/blob/master/blueprints/ember-cli-mocha/files/tests/test-helper.js that code should not be in the `helpers/resolver.js` file, but in `test-helper.js` instead.

**Comment by marclundgren** [comment]
thanks @Turbo87
