### ISSUE TITLE
component unit test with needs: [] still throws ember-test-helper deprecation

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember-mocha#129]
I noticed this in one of my apps as I was upgrading to the new syntax and it's easily reproduced.

Example app showing the problem:

https://github.com/blimmer/ember-cli-example-app-for-github/compare/ember-mocha/issue-129

Failing build because of the deprecation (from ember-cli-deprecation-workflow):

https://travis-ci.org/blimmer/ember-cli-example-app-for-github/builds/194621068

**Comment by Turbo87** [comment]
@blimmer I think this is actually an issue in https://github.com/emberjs/ember-test-helpers since we're basically just passing through those options. Can you make sure to open an issue there too and crosslink it?

**Comment by blimmer** [comment]
@Turbo87 I'm definitely not an expert in this code, but it looks like the `needs` array is gone in the mocha / ember-mocha layer before it passes on to ember-test-helpers.

<img width="672" alt="screen shot 2017-01-26 at 12 04 57 pm" src="https://cloud.githubusercontent.com/assets/630449/22346076/dcbbcf7a-e3bf-11e6-8eb1-69d2c3a6a597.png">

**Comment by blimmer** [comment]
Strangely enough, `unit: true` is still getting passed through...

<img width="783" alt="screen shot 2017-01-26 at 12 19 39 pm" src="https://cloud.githubusercontent.com/assets/630449/22346548/c26d4c28-e3c1-11e6-9b71-93864abd8b09.png">

**Comment by blimmer** [comment]
Yep, you're right @Turbo87 , this is an upstream problem and even seem like it might be related to a change that you made:

https://github.com/emberjs/ember-test-helpers/blame/d5c50d0058e141aff0b3b7ed72932e6eca6e6ece/lib/ember-test-helpers/test-module-for-component.js#L29

maybe you have some insight into the right fix.

Either way, this will be handled upstream - thanks for the help. Closing.
