### ISSUE TITLE
setupAcceptanceTest not invoking destroy-app

### ISSUE THREAD

**Issue by ming-codes** [emberjs/ember-mocha#133]
Not sure if this belong in `ember-mocha` or `ember-test-helpers`

`ember-cli-mirage` uses `tests/helpers/destroy-app.js` to clean up after each test. It doesn't looks like there's anything in `setupAcceptanceTest` that tries to invoke this.

**Comment by Turbo87** [comment]
@ming-codes `setupAcceptanceTest()` does setup an `afterEach()` block that destroys the application, but you are correct that it does not run the `server.shutdown()` command that `ember-cli-mirage` [inserts](https://github.com/samselikoff/ember-cli-mirage/blob/master/blueprints/ember-cli-mirage/index.js#L40). You should be able to do this manually like this:

```js
describe('Acceptance | /foo', function() {
  setupAcceptanceTest({ application });

  afterEach(function() {
    server.shutdown();
  });

  it('works', function() {
    // ...
  });
});
```

you could also extract that into a custom `setupAcceptanceTest()` function that handles both things for you.
