### ISSUE TITLE
this.inject.service(...) is not working

### ISSUE THREAD

**Issue by ming-codes** [emberjs/ember-mocha#134]
```js
describe('Unit @ validator:user/roles', function() {
  setupTest('validator:user/roles', {
    needs: ['validator:messages', 'service:store']
  });

  it('should detect user with no roles.', async function() {
    this.inject.service('store');
    console.log(this.store); // nope
  });
});
```

Investigation shows that `this` is not the instance of `context` that inject is setting to. So injection is working..just on the wrong object.

**Comment by ming-codes** [comment]
https://github.com/emberjs/ember-mocha/blob/master/lib/ember-mocha/setup-test-factory.js#L22

This line?

We're copying over the properties from `ember-test-helpers` context, but `ember-test-helpers` is actually using a lexically bound `context`

https://github.com/emberjs/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module.js#L139

**Comment by ming-codes** [comment]
#111 is related

**Comment by basicBrogrammer** [comment]
Having the same problem

**Comment by efx** [comment]
I am also seeing this issue. In our app's `test-helper.js` file, I am setting a property in the root level `before` hook:
```js
before(function() {
	this._sandbox = sinon.sandbox.create();
});
```
When a test  accesses `this._sandbox` within a `beforeEach`, the suite fails to load because `this._sandbox` is undefined.

**Comment by efx** [comment]
@ming-codes thanks for those links but they return 404s now.

**Comment by Turbo87** [comment]
with the new testing APIs released in v0.14.0 `this.inject.service()` is no longer a thing. instead you would do e.g. `this.intl = this.owner.lookup('service:intl');`

**Comment by ming-codes** [comment]
Does ember mocha handles the context clean up now? Mocha itself retains all context objects of the whole test suite, which can be leaky if we are to attach container instantiated objects on the context object.

**Comment by Turbo87** [comment]
[this](https://github.com/emberjs/ember-mocha/blob/master/addon-test-support/ember-mocha/setup-test.js#L47)?

**Comment by ming-codes** [comment]
Yup, that’s it.
