### ISSUE TITLE
newAttrs in didReceiveAttrs is empty

### ISSUE THREAD

**Issue by KamiKillertO** [emberjs/ember-mocha#139]
Hello,

I'm trying to test a component which use the `didReceiveAttrs` hook to format data.
I've try different things but `newAttrs` in `didReceiveAttrs` is always empty.

**Comment by Turbo87** [comment]
as you can see in http://emberjs.com/api/classes/Ember.Component.html#method_didReceiveAttrs the `didReceiveAttrs()` hook receives no arguments

**Comment by KamiKillertO** [comment]
Indeed the arguments of `didReceiveAttrs ()` disappeared in Ember2.x.
I was watching an old documentation 😞, sorry for this disturbance.
