### ISSUE TITLE
consider deprecating callbacks

### ISSUE THREAD

**Issue by cowboyd** [emberjs/ember-mocha#14]
`describeModule` and friends accept a list of callbacks. E.g.

``` js
describeModule('component:x-foo', 'TestModule callbacks', {
  beforeSetup: function() {},
  setup: function() {},
  teardown: function() { },
  afterTeardown: function() {}
, function() {
// spec body
})
```

After using ember mocha for a while, I feel that using the callbacks mechanism is unnecessary and a result of limitations in qUnit leaking through the shared interface. The reason is because, unlike qUnit, mocha has a generalized setup and teardown api in the form of `before{All,Each}` and `after{All,Each}` hooks, I have yet to encounter a situation where they have not sufficed.

While they could remain optional via, they feel counter to the mocha way and so should not occupy such a prime portion of API real-estate. At the very least, I think that the ember cli blueprints should generate idiomatic mocha code that does setup and teardown inside before and after hooks.

**Comment by rwjblue** [comment]
@cowboyd - As long as the context of `{before,after}{All,Each}` is the same as the `it` blocks (I believe it should already be true), then I'd say lets review a PR in ember-cli-mocha changing the blueprints...

**Comment by rwjblue** [comment]
Hmm, it seems that the `beforeEach`/`afterEach` (etc) callbacks do not get the same test context.

https://github.com/switchfly/ember-mocha/blob/master/lib/ember-mocha/mocha-module.js#L21-L37 is where the callbacks are setup, and it does not seem that we are overriding these to set the proper context.

**Comment by cowboyd** [comment]
It does as of #6, 

I'll open an issue on ember-cli-mocha and see if I can get around to it at some point.

**Comment by rwjblue** [comment]
@cowboyd - Awesome, I did not see that.  I think we should have some tests for #6 to ensure it works properly (I reviewed the tests to see if it were supported).  For example I added some tests confirming context in https://github.com/switchfly/ember-test-helpers/pull/12, maybe they could be used to ensure #6 does not have regressions...

**Comment by Turbo87** [comment]
@cowboyd I think this can be considered solved, right? I'll close this, but feel free to reopen if I'm wrong!

**Comment by cowboyd** [comment]
@Turbo87 Yes, I believe it is solved, and the blueprints have been updated for some time. Thanks!
