### ISSUE TITLE
`TypeError: factory.create is not a function` when trying to create a unit test for a helper

### ISSUE THREAD

**Issue by marclundgren** [emberjs/ember-mocha#140]
Hello. I need to write unit tests for my `helper` like I would with `qunit`. However, It's looking like `ember-mocha` won't allow that.

Here's my simple test

```js
import { expect } from 'chai'
import { describe, it } from 'mocha'
import { setupTest } from 'ember-mocha'

describe('PercHelper', function() {
  setupTest('helper:perc')

  it('exists', function() {
    var helper = this.subject()
    expect(helper).to.be.ok
  })
})

```

**Comment by Turbo87** [comment]
@marclundgren helpers are usually not classes (or `Ember.Object`s) and so they don't necessarily have a `.create()` method. You can look into https://github.com/emberjs/ember.js/blob/master/blueprints/helper-test/mocha-0.12-files/tests/__testType__/helpers/__name__-test.js to find out how unit and/or integration tests for helpers are supposed to look like.
