### ISSUE TITLE
Is it possible to use this package without bower?

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember-mocha#142]
I'm trying to remove bower from my ember project, which is supported in ember-cli v2.12. I've moved `ember-mocha` into my package.json, but can't `import { setResolver } from 'npm:ember-mocha'`, because the npm package only includes the source and not the compiled assets.

**Comment by aexmachina** [comment]
This is a non issue 👍

**Comment by efx** [comment]
For later travelers, this is a non-issue because when you install `ember-cli-mocha@0.14.0` (or greater), it includes the `ember-mocha` and `mocha` dependencies for you.

**Comment by Turbo87** [comment]
yep, same for `ember-cli-test-loader` (see https://github.com/ember-cli/ember-cli-mocha/pull/129) and Chai.js once you have a npm dependency on `ember-cli-chai`
