### ISSUE TITLE
Unable to run all tests in a fresh checkout of master

### ISSUE THREAD

**Issue by jbryson3** [emberjs/ember-mocha#148]
It run the jsHint tests but not much else
Terminal output has:
> 'require' is imported by tmp/rollup-cache_path-GK58QtLK.tmp/ember-test-helpers/build-registry.js, but could not be resolved – treating it as an external dependency
'require' is imported by tmp/rollup-cache_path-GK58QtLK.tmp/ember-test-helpers/test-module-for-model.js, but could not be resolved – treating it as an external dependency

Console output has:
> loader.js:58 Uncaught Error: Could not find module require
    at requireModule (loader.js:58)
    at reify (loader.js:41)
    at requireModule (loader.js:69)
    at reify (loader.js:41)
    at requireModule (loader.js:69)
    at reify (loader.js:41)
    at requireModule (loader.js:69)
    at TestLoader.loadModules (test-loader.js:16)
    at Function.TestLoader.load (test-loader.js:23)
    at test-loader.js:26

All the tests start running again if I use ember-test-helpers: 0.6.2
Seems to be trouble with ember-test-helpers: 0.6.3

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-mocha/pull/147 should have fixed this, and CI was green when it landed...

**Comment by Turbo87** [comment]
@rwjblue we don't have any jshint tests anymore in this repository. it seems like @jbryson3 might be talking about his own test suite.

**Comment by rwjblue** [comment]
Ah, I see. 

I think a demo reproduction would be super helpful here...

**Comment by jbryson3** [comment]
@rwjblue #147 was not merged into Master. I didn't realize that v0.11.x was the active branch that I should be using.

@Turbo87 I apologize, I meant to say ESLint tests, not jshint. I was attempting to run the test suite of ember-mocha.

I was attempting to run the suite of tests from the master branch that last had a commit in January (f5758108556a62dfeee1d7f70fc978b5b63505f0)

Tests are working fine on the v0.11.x branch

**Comment by rwjblue** [comment]
AHA! I didn't realize that commit wasn't on master though.  I'm guessing that @Turbo87 just needs to merge that fix up into master?

**Comment by Turbo87** [comment]
> I'm guessing that @Turbo87 just needs to merge that fix up into master?

yeah, that will need to happen soonish...
