### ISSUE TITLE
setupAcceptanceTest() issues

### ISSUE THREAD

**Issue by k3n** [emberjs/ember-mocha#149]
Greetings,

I'm trying to use `setupAcceptanceTest()` and have a few questions/problems:

1. The `Application` seems to never get created -- I added a `console.log` / `debugger` in the `create()` method, and it never hits. I've also tried the alternative method signature mentioned in #131 (btw, are there plans for a fixed release anytime soon? That fix has been hanging out for 4? months).
2. Assuming `setupAcceptanceTest()` worked as expected, how might I access the resultant application instance? `setupAcceptanceTest()` doesn't appear to return anything, so I'm unsure how I might be able to access it. This is required for integration with `ember-simple-auth`'s [test helpers](https://github.com/simplabs/ember-simple-auth#testing).

**Comment by Turbo87** [comment]
you might be running into the same issue as https://github.com/emberjs/ember-mocha/issues/131. please let me know if you still have issues using the `v0.12.0` release.
