### ISSUE TITLE
setupAcceptanceTest can't use application.__container__.lookup('service:session') ?

### ISSUE THREAD

**Issue by caseywatts** [emberjs/ember-mocha#151]
When trying to migrate a test to the new suite, I get this error:

```
TypeError: Cannot read property 'get' of undefined
```

I'm calling `torii`'s `stubValidSession` [defined here](https://github.com/Vestorly/torii/blob/4146248531f54dd60f10946eb75c8d50e4cd8865/test-support/helpers/torii.js#L3) in a `beforeEach`, passing `this.application`.

It seems like `torii` expects `application.__container__.lookup('service:session')` to work. The function `application.__container__.lookup` is there, but it doesn't return anything from that call.  It works for me with the old mocha setup format (`startApp` and `destroyApp`), but not with the new one `setupAcceptanceTest`.

Although this could potentially be an issue on torii's side of things - I thought to put it here since it seems like `torii` is doing a pretty reasonable/common thing there ^

Are we doing anything weird with the new style of setup vs the old that could cause services not to be registered anymore?

**Comment by Turbo87** [comment]
> Are we doing anything weird with the new style of setup vs the old that could cause services not to be registered anymore?

not that I'm aware of... the code that is running internally is pretty similar and calling the same `ember-test-helpers` APIs, it just looks a little different from the outside.

**Comment by caseywatts** [comment]
hmm!
I'm opening an issue in `ember-mocha` too then - thanks for responding so quickly! :)

**Comment by Turbo87** [comment]
you might be running into the same issue as #131. please let me know if you still have issues using the v0.12.0 release.
