### ISSUE TITLE
Question: Does the ability to use multiple resolvers work? 

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/ember-mocha#153]
Howdy,
 I noticed in the docs a really handy bit of advice:

"If you want to use multiple resolvers in your test suite, you can also call setResolver in the beforeSetup callback of your test modules."
https://github.com/emberjs/ember-mocha#setting-the-resolver

 But I was curious because there is no callback named beforeSetup .. or did you mean beforeEach?

**Comment by Turbo87** [comment]
I have never actually used that feature myself, but I agree that this is probably a typo and should be `beforeEach`. Could you open a pull request to fix this?

**Comment by Turbo87** [comment]
One potential way to do this is use a custom resolver that delegates to two or more child resolvers. You should be able to use `setResolver()` with that pattern.
