### ISSUE TITLE
How to test a component mixin?

### ISSUE THREAD

**Issue by mattmarcum** [emberjs/ember-mocha#176]
I'm trying to upgrade an older app and it had a unit test that created a generic component (with a mixin) and set it on the resolver.  Looks like ember-mocha could resolve the newly created component for its test:

```js
describeComponent('sliding-drawer', 'SlidingDrawerComponent', {
    unit: true,
    needs: ['service:sliding-drawer-manager']
  }, function() {
    before(function() {
      resolver.set('registry', {
        'component:sliding-drawer': Ember.Component.extend(SlidingDrawerComponentMixin)
      });
    });
...
```

Looks like the test suite was using a customer resolver.  I'm trying to migrate everything to use the default setup and get rid of the custom resolver.

My question is - what's the correct way to test mixins, specifically mixins for components that need to be `rendered`, etc...

**Comment by efx** [comment]
@mattmarcum welcome! To assert mixin behavior, use plain `describe` and `it` functions imported from mocha. While you could test those within a component unit test, it will be more difficult as there is another layer between the behavior and the tests asserting that behavior. 
For better help and examples, I would recommend joining the ember discuss forum and posting here: https://discuss.emberjs.com/c/testing.
