### ISSUE TITLE
Finalize new testing API

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember-mocha#198]
Just to not forget it, we talked about this on Slack, the current support for the new testing APIs in master includes a currently dubbed `setupContainerTest()` function (the equivalent of `setupTest()` in QUnit), the naming of which is a bit controversial. So this should be finalized before master is released.

I'll try to layout some alternatives (feel free to extend):

## Reuse `setupTest()`

Having that function be named `setupTest()` would be the best, as this is how it is called for QUnit. However this function is already used for the old testing APIs in ember-mocha. Usually it expects the name of the test as its first argument, but the current implementation also allows to skip this argument and only supply a hash ([here](https://github.com/emberjs/ember-mocha/blob/master/addon-test-support/ember-mocha/setup-test-factory.js#L9-L12)). So we cannot use this function for both testing APIs without conflicts...

### Disambiguate by using some differentiating arguments

We could require some arguments to be present for this function to work with the new testing APIs:

```js
setupTest({ ... }, true); // second arg is opt in flag
setupTest({ ..., new: true }); // some flag inside the options hash
```

When support for the old APIs can be dropped totally (after some transition period), we can remove the requirement for this flag. But it would then still be around in existing codebases, so not 100% optimal IMHO.

### Rely on first argument being the test name

We could rely on the first argument to be string to use the old APIs, as this is *probably* the way this function is used in almost all cases (generated by blueprints). However as mentioned this is not required currently, so for those not doing this, this would be a *breaking change*:

```js
setupTest('controller:foo', { ... }); // old API
setupTest({ ... }); // new API
```

## Rename `setupContainerTest()`

Continue to use a differently named function, but some alternative name. Some suggestions:

* `setupContextTest()`
* `setupEmberTest()`
* `setupOwnerTest()` (`owner` being a public API, instead of the private `container`)

/cc @Turbo87 @rwjblue

**Comment by Turbo87** [comment]
For obvious reasons I would still prefer the first solution relying on the first arg being a string. I think if we properly mark it as a breaking change then it should be fine.

**Comment by simonihmig** [comment]
> For obvious reasons I would still prefer the first solution relying on the first arg being a string. I think if we properly mark it as a breaking change then it should be fine.

Happy about this as well! 👍

I can create a PR later if we settle on that! @rwjblue ok for you as well?

**Comment by rwjblue** [comment]
Yes, that seems ideal to me also...
