### ISSUE TITLE
Testing action invocation with new API

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember-mocha#203]
I'm migrating my tests to the new `setupRenderingTest()` API and realized that `this.on` is not part of the new API. How do you set up an action and verify that your component invoked it correctly now?

**Comment by alexlafroscia** [comment]
It seems like you can migrate from

```
// before
const onClick = td.function();
this.on('onClick', onClick);

await render(hbs`
  <button {{action 'onClick'}}>Click me</button>
`);
```

to this:

```
// after
const onClick = td.function();
this.set('onClick', onClick);

await render(hbs`
  <button {{action onClick}}>Click me</button>
`);
```

Is this the recommendation? It might be worth calling out in the migration guide.

**Comment by Turbo87** [comment]
@alexlafroscia yep, that is what the `ember-qunit-codemod` does too iirc

**Comment by alexlafroscia** [comment]
Ahh, okay. I didn't run the codemod, just did the migration by hand.

Would you want a PR to the migration docs that explain the pattern?

**Comment by Turbo87** [comment]
> Would you want a PR to the migration docs that explain the pattern?

I guess that would make sense, yeah. @simonihmig any thoughts on this?

**Comment by simonihmig** [comment]
Yeah, that seems reasonable! 👍

**Comment by alexlafroscia** [comment]
Closing since we've confirmed the path forward and I made a PR that mentions this in the migration guide.
