### ISSUE TITLE
Confusing doc when using latest stable version

### ISSUE THREAD

**Issue by lewazo** [emberjs/ember-mocha#207]
It is kind of confusing and misleading that the README on the master branch describes how to use ember-mocha with the new testing API since it is only available in the pre-release.

Typically, someone wanting to integrate this add-on to their projet would go on the GitHub repo, follow the steps to install the add-on, then do a `ember install ember-mocha`. When doing so, they'll end up with the latest stable release which is the 0.13.x. Which of course does not support the new API, so following the next steps will lead to a `(0, _emberMocha.setupApplicationTest) is not a function` error and other not-so-obvious errors when using `setupTest()` without any arguments (`Cannot read property 'split' of undefined`).

It might be a good idea to specify that it is currently only available on the beta version, and for those using the latest stable version (basically everyone who followed the first step on how to install) should use the Legacy Guide.

**Comment by Turbo87** [comment]
see https://github.com/emberjs/ember-mocha/issues/205#issuecomment-394649947
