### ISSUE TITLE
The `setTimeout` in test runner throws a warning in console

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember-mocha#208]
The offending line is here:

https://github.com/emberjs/ember-mocha/blob/7833e14349f5136802d7a6bbe89bca34f97329e7/vendor/ember-mocha/test-loader.js

And the error looks like this:

<img width="1048" alt="screen shot 2018-05-31 at 2 52 59 pm" src="https://user-images.githubusercontent.com/75710/40810616-2ec3ac0c-64e3-11e8-9ed3-4d9f08a5a16c.png">

After reading through the issues listed in comments above the `setTimeout` it seems like this is a legacy fix for sourcemaps.  Is this code still necessary?

**Comment by rwjblue** [comment]
FYI - `ember-qunit` removed the delayed starting completely, in favor of users doing `import { start } from 'ember-qunit'` and calling `start()` explicitly...

**Comment by rondale-sc** [comment]
@rwjblue I saw that.  I'm still a bit unclear as to when it knokws it is safe to call `start`

**Comment by rwjblue** [comment]
well, there is no "safe" it just starts when you invoke it 😝

**Comment by Turbo87** [comment]
this got resolved in https://github.com/emberjs/ember-mocha/pull/281
