### ISSUE TITLE
Can't generate acceptance tests

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/ember-mocha#213]
I'm attempting to set up a new Ember 3.3 project using `ember-cli-mocha`. It installs `ember-mocha` 0.13.1 by default, but it seems that I need to update `ember-mocha` to use new-style async testing. When I install `ember-mocha` 0.14.0, though, it seems like I can no longer generate acceptance tests with `ember g`.

Here is a branch of my mostly-empty project that exhibits the problem. The final commit in the branch is what upgrades `ember-mocha` to 0.14.0 and where the problem starts occurring: https://github.com/CodingItWrong/bible-reading-ember/tree/acceptance-test-troubleshooting

Before upgrade:

```
~/apps/bible-reading/client [acceptance-test-troubleshooting] # ember generate acceptance-test smoke
installing acceptance-test
  create tests/acceptance/smoke-test.js
~/apps/bible-reading/client [acceptance-test-troubleshooting] #
```

After upgrade:

```
~/apps/bible-reading/client [acceptance-test-troubleshooting] # ember generate acceptance-test smoke
installing acceptance-test
~/apps/bible-reading/client [acceptance-test-troubleshooting] #
```

This problem is also occurring in [an Ember 3.1 app of mine](https://github.com/CodingItWrong/firehose) using `ember-mocha` 0.14.0-beta.1

Please let me know anything I can do to help troubleshoot!

**Comment by Turbo87** [comment]
@CodingItWrong https://github.com/emberjs/ember.js/pull/16865 added support for standalone `ember-mocha` and the new APIs in Ember itself, unfortunately it is only available in Ember 3.6 and above.
