### ISSUE TITLE
Context.owner is undefined (and exceptions are swallowed)

### ISSUE THREAD

**Issue by richard-viney** [emberjs/ember-mocha#256]
Hi,

I'm trying to use v0.14 to try out the new testing approach, and running into some problems.

The main issue is that component tests time out in the setup phase, which is happening because the `context` being passed into `setupRenderingContext()` doesn't have `owner` set (it's undefined). This results in an exception, which is swallowed (not sure by what), and there is then a timeout being reported for the affected test.

Questions:

1. Where is `context.owner` meant to be set? I'm assuming there's some config problem in my app, but don't really know where to start looking. `test-helper.ts` is being executed and is calling `setApplication.

2. The actual exception being thrown here (`Cannot read property '_emberTestHelpersMockOwner' of undefined`) is being swallowed and turned into a timeout - presumably because a promise chain never terminated. This hides errors and seems undesirable?

Any help is appreciated.

Thanks.

**Comment by richard-viney** [comment]
This was entirely my error - the `start-app.ts` file wasn't correctly returning the `application` object.

Is there anything worth fixing in that exception swallowing issue though?

**Comment by Turbo87** [comment]
@richard-viney if you can come up with a minimal reproduction of the issue we can look into it

**Comment by richard-viney** [comment]
Closing as I think this was largely self-inflicted.
