### ISSUE TITLE
ember-mocha tests failing with Ember 3

### ISSUE THREAD

**Issue by a13o** [emberjs/ember-mocha#258]
In this repo if you run all the tests by visiting `http://localhost:4200/tests` they will pass. But if you try to narrow the scope with the grep param, tests will fail which rely on the resolver helper.

visiting `http://localhost:4200/tests?grep=setupComponentTest` will produce
```
setupComponentTest
    x-foo component
        "before each" hook for "renders" 
            TypeError: this.registry is undefined
```

Could be due to the registry deprecations in 2.x that were removed in 3.

**Comment by Turbo87** [comment]
can you provide a repository that reproduces this issue?

**Comment by a13o** [comment]
I was seeing it on my fork which is up to date with master https://github.com/a13o/ember-mocha

**Comment by a13o** [comment]
I'm not able to repro this anymore with the latest master. May have been another package bump or updating my ember-cli.
