### ISSUE TITLE
Set 'timeout' globally?

### ISSUE THREAD

**Issue by Chun-Yang** [emberjs/ember-mocha#28]
In mocha, we can set global timeout by adding `test/mocha.opts` file:

```
--timeout 5000
```

Is there a way to do this in ember-mocha?

**Comment by blimmer** [comment]
I would also love to know how to do this.

**Comment by wongpeiyi** [comment]
I could do this in my test-helper.js
```javascript
mocha.setup({
  timeout: 10000,
  slow: 2000
});
```

**Comment by jimmay5469** [comment]
Thanks @wongpeiyi, this worked for me as well!

**Comment by grantovich** [comment]
I'm also looking for a way to set or disable the timeout globally. Just tried @wongpeiyi's solution, but it did not work for me (the timeout was still 2000ms). Is there a trick besides just adding that code to your `test-helper.js`?

**Comment by mattmcmanus** [comment]
The conversation here isn't clear. @wongpeiyi What other setup do you need in your test-helper for that to work? Is there anyway to increase the timeout a bit? the 2 second timeout constantly triggers for me if my browser's been open for a while.

**Comment by wongpeiyi** [comment]
I'm sorry, I can't guess why it wouldn't work. That was on ember 1.11 and ember-mocha 0.6.2, no other setup needed. 

The documentation is here: http://mochajs.org/#browser-configuration
I agree it's not a good solution though.

**Comment by mupkoo** [comment]
I tried this and the interesting part is that you have to use the global mocha object.
When ever you do one of the following, it is not working

```javascript
import mocha from 'mocha';
import mocha from 'ember-mocha';
```

**Comment by blimmer** [comment]
For those looking to make this work: do this in your `tests/test-helper.js` file.

```javascript
import { mocha } from 'mocha';

mocha.setup({
  // customize as needed
  timeout: 5000,
  slow: 1000,
});
```

@wongpeiyi 's comment was correct, but I had to figure out how to grab mocha from the ES6 import.

**Comment by Turbo87** [comment]
@blimmer thanks for clearing that up!
