### ISSUE TITLE
TypeError: Cannot read property 'reopen' of undefined

### ISSUE THREAD

**Issue by DWC01** [emberjs/ember-mocha#322]
Hey there, 

I just upgraded to the latest `ember-mocha` and can't seem to shake the below error. I am running this test (setup outlined below) in the browser by visiting `http://localhost:4200/tests`, and when I do, I can see that this test actually passes with a green checkmark, however, it is then followed by the below error message. It also seems to be intermittent, showing up about 6/10 times when I run the below test.

Error I see displaying in the UI right below my passing test:

```
X  "after each" hook for "visits login page"

TypeError: Cannot read property 'reopen' of undefined
    at Class.dropObject (<anonymous>:2956:18)
    at Class.willDestroy (<anonymous>:2929:18)
    at Class.superWrapper (assets/vendor.js:42349:28)
    at invoke (assets/vendor.js:60112:24)
    at Queue.flush (assets/vendor.js:60033:25)
    at DeferredActionQueues.flush (assets/vendor.js:60185:31)
    at Backburner._end (assets/vendor.js:60615:42)
    at Backburner.end (assets/vendor.js:60418:18)
    at Backburner._run (assets/vendor.js:60658:26)
    at Backburner.run (assets/vendor.js:60453:25)
```

My current setup:
```
ember-cli: 3.7.1
ember-mocha:  ^0.14.0
ember-cli-mocha: ^0.15.0
```

/tests/test-helper.js
```
import Application from '../app';
import config from '../config/environment';
import { setApplication } from '@ember/test-helpers';

setApplication(Application.create(config.APP));
```

/tests/acceptance/example-test.js
```
import { expect } from 'chai';
import { describe, it } from 'mocha';
import { setupApplicationTest } from 'ember-mocha';
import { visit, currentURL } from '@ember/test-helpers';

describe('basic acceptance test', () => {
  setupApplicationTest();

  it('visits login page', async () => {
    await visit('/login');
    expect(currentURL()).to.equal('/login');
  });
});
```

/app/config/environment.js
```
if (environment === 'test') {
    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
    ENV.host = 'http://localhost';

    ENV.APP.autoboot = false;
  }
```

Have you seen this error pop up before? Does anything look incorrect with this current setup for running mocha tests in Ember with the new api? My tests were running as expected before the api update, and the tests are actually passing, seems like something is just getting messed up during tear town. Thanks.

**Comment by Turbo87** [comment]
@DWC01 thanks for reporting this issue. can you click on the callstack and see what the code looks like that is trying to call `.reopen()`? it seems a little strange to me that the `willDestroy()` hook would call `reopen()` by default, so I'm assuming something is maybe overriding it 🤔

**Comment by mattgraham1995** [comment]
For anyone else looking for a solution to this issue, I had this problem when I upgraded to Ember 3.8. My qunit tests were failing with the same callstack in the afterEach block. I fixed it by adding `ember-template-compiler` to my package.json. My app uses it for a custom test helper so we import it in  `ember-cli-build.js`. 

`app.import('vendor/ember/ember-template-compiler.js');`

**Comment by psbanka** [comment]
Also seems to be a "feature" of the latest Chrome Canary build (Version `76.0.3805.0`)

**Comment by DWC01** [comment]
Hey @Turbo87 , sorry for delayed response here, actually just picking up where I left off now with testing this Ember project..  In this case I upgraded `ember-mocha` to `v0.15.1` (also removed `ember-cli-mocha` per the upgrade instructions on the [README](https://github.com/ember-cli/ember-cli-mocha)) and everything seems to be working as expected. I still haven't narrowed down what caused the issue originally described in this ticket but upgrading and removing `ember-cli-mocha`  seemed to fix this for me. I'll close the ticket as things seems to be working as expected using `v0.15.1`, thanks.

**Comment by chbonser** [comment]
I've seen this a few times (most recently today). Restarting chrome resolved the issue.

**Comment by allthesignals** [comment]
Seeing this same issue as well, but using ember-qunit not ember-mocha. Restarting Chrome fixed it 🤔

**Comment by zubeir68** [comment]
> I've seen this a few times (most recently today). Restarting chrome resolved the issue.

Restarting chrome did it for me :)) :+1:
