### ISSUE TITLE
Is start() api ready to be released?

### ISSUE THREAD

**Issue by step2yeung** [emberjs/ember-mocha#356]
@Turbo87 I was wondering if changes to introduce `start()`, moving away from autostart using timeout is ready to be released? 

The changes in ember-exam v3.0 no longer monkey patch the ember-cli test loader, and would be able to support ember-mocha properly if the above gets released. Related to [ember-exam #238](https://github.com/ember-cli/ember-exam/issues/238)
fyi @stefanpenner

**Comment by Turbo87** [comment]
I assume you're talking about https://github.com/emberjs/ember-mocha/pull/281, right? I guess we could release that, yeah.

**Comment by step2yeung** [comment]
yes please @Turbo87 !

**Comment by Turbo87** [comment]
@step2yeung released as v0.15.0

**Comment by step2yeung** [comment]
@Turbo87 Awesome! Thanks for releasing!
