### ISSUE TITLE
start() function isn't in @types/ember-mocha

### ISSUE THREAD

**Issue by richard-viney** [emberjs/ember-mocha#371]
For TypeScript projects, a type for the `start()` function is missing from `@types/ember-mocha`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember-mocha/index.d.ts

Not sure if this should this issue belongs to this project, or on `ember-cli-typescript`.

**Comment by Turbo87** [comment]
I don't know who maintains these typings, but it's not us. I'm sure PRs to the typings are welcome though :)
