### ISSUE TITLE
integration tested components do not respond to jquery DOM events like qunit

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember-mocha#41]
It seems that there's a difference between ember-mocha and ember-qunit, in handling jquery-triggered DOM events in an `integration: true` test.

DOM event triggers work in qunit:
- [PR with additional passing tests to ember-test-helper](https://github.com/switchfly/ember-test-helpers/pull/66/files#diff-7d23635c0b737f5e0d44ff0d95a9c20cR93)
- [Example App](https://github.com/blimmer/ember-working-integration-tests-qunit/) with [failing test](https://github.com/blimmer/ember-working-integration-tests-qunit/blob/master/tests/unit/components/my-input-test.js#L11) and [passing travis build](https://travis-ci.org/blimmer/ember-working-integration-tests-qunit/builds/68191312)

But these events don't trigger in mocha:
- Sorry, I couldn't figure out how to write failing tests here, because there are no tests for `integration: true` that I could easily build off of
- [Example app](https://github.com/blimmer/ember-broken-integration-tests-mocha) with [failing test](https://github.com/blimmer/ember-broken-integration-tests-mocha/blob/master/tests/integration/components/my-input-test.js#L16) and [failing travis build](https://travis-ci.org/blimmer/ember-broken-integration-tests-mocha/builds/68191979)

Please let me know if there's any additional information I can provide.

**Comment by blimmer** [comment]
@slindberg found a workaround for this on [this PR](https://github.com/blimmer/ember-broken-integration-tests-mocha/pull/1). It makes the tests pass, but he has to wrap it in an `Ember.run`. This is a decent workaround for others experiencing this problem, but it seems like the behavior should be the same between Qunit and Mocha.

**Comment by dgeb** [comment]
@blimmer @slindberg that's a great start for getting to the bottom of this. Thanks!

**Comment by slindberg** [comment]
I suspect this issue might be at the adapter level. @teddyzeenny can you shed some light on this?

**Comment by teddyzeenny** [comment]
The adapter is responsible for handling async tests and exceptions. I don't think triggering DOM events in integration tests is adapter related. Even though unlikely, if it does turn up to be an adapter issue, I'm happy to work on a fix.

**Comment by devinus** [comment]
It is damn near impossible to integration test components with Mocha right now.

```js
    it('selects a stack', function(done) {
      this.on('changeStack', function(value) {
        expect(value).to.equal('s2');
        done();
      });

      this.render(hbs`{{salesforce-integration stack='s1' action='changeStack'}}`);
      expect(this.$('#salesforce-stack').val()).to.equal('s1');

      Ember.run(this.$('#salesforce-stack').val('s2'), 'trigger', 'change');
    });
```

This code is calling my `changeStack` action on the component but not my `on` hander.

**Comment by blimmer** [comment]
I agree with you @devinus - I really wish there was a better solution than this (especially because acceptance tests have such convenient methods `click`, `fillIn`, etc.)

Based on the acceptance test flavors, I've derived some helpers we use. Perhaps they will help you:

```javascript
var componentTriggerEvent = function (component, selector, eventName, options) {
  if (options == null) {
    options = {};
  }

  var $selector = componentSelector(component).find(selector);

  Ember.run($selector, 'trigger', eventName, options);
};


var componentFillInput = function(component, selector, value) {
  var $selector = componentSelector(component).find(selector);
  $selector.val(value);
  componentTriggerEvent(component, selector, 'input');
  componentTriggerEvent(component, selector, 'change');
};
```

**Comment by Turbo87** [comment]
it seems that https://github.com/cibernox/ember-native-dom-helpers essentially resolves this issue. if there are still problems please let me know.
