### ISSUE TITLE
Why is it advised to set the resolver once for tests?

### ISSUE THREAD

**Issue by hwhelchel** [emberjs/ember-mocha#44]

**Comment by Turbo87** [comment]
@rwjblue @dgeb @trentmwillis any ideas? I have to admit I don't know the answer to this one either...

**Comment by trentmwillis** [comment]
The reason for this is that `setResolver` won't "reset" after a given test ends. So, you're essentially mucking with global state which could potentially cause problems in your test suite.

That said, ember-test-helpers now provides an easy way to set a resolver for a given test module: https://github.com/emberjs/ember-test-helpers/pull/174.
