### ISSUE TITLE
Using ember-mocha without Ember Data

### ISSUE THREAD

**Issue by oliverbarnes** [emberjs/ember-mocha#49]
I'm using [ember-jsonapi-resources](https://github.com/pixelhandler/ember-jsonapi-resources) instead of ED, and am having trouble using ember-mocha to test a model. Tried `describeModel`, `describeModule`, and `describe` blocks, each time running into different problems loading the test and recognizing the helpers.

Looking at the source, though I'm still far from understanding what's going on there, I see `DS` shows up quite a few times.

I was hoping to stick to mocha, being from rspec-world, by using simple `describe` blocks and looking up the container directly to define the subjects of tests. Is there a way to do it?

Btw, are there plans to decouple EM from ED?

**Comment by rwjblue** [comment]
* What are you trying to test?
* What version of ember-mocha are you using?

>  are there plans to decouple EM from ED

They are not directly coupled, but the `describeModel` here (and upstream in ember-test-helpers) make a few assumptions that are ED specific.  I'm absolutely in favor of abstracting a common interface for this stuff, but would need one of the authors of an alternative framework to step up and offer to help out with this.

**Comment by oliverbarnes** [comment]
I'm happy to help with this, but would need guidance in the changes that need to be done. Would be a great way to boost my ember fu, which is pretty white belt at the moment

**Comment by oliverbarnes** [comment]
cc @pixelhandler

**Comment by pixelhandler** [comment]
@rwjblue In ember-jsonapi-resources (an ember-cli addon) for data persistence following the JSON API spec I use `service:store` (so does Ember data) and use initializers to register model factories in the container like so `application.register('model:authors', Model, { instantiate: false, singleton: false })` ( `Model` is an import e.g. `import Model from '../models/author';` ).

I had trouble using the singular form of the model name when registering the model factory. Not sure why. Also, there I found documentation to setup the EmberEnv with `MODEL_FACTORY_INJECTIONS: true`. Not sure if that matters or not but that's what I was able to find.

Basically I think any persistence solution for an app using ember-cli should be able to use the models in the container as well as a store service. I think that at testing framework or runner specially for use in and ember-cli app would afford the same. The store service may or may not have the same interface as ember data's store service and the same goes for the model factories. For Ember QUnit I just went with using pluralized naming for models and also related service, adapter, and serializer. So in the setup and teardown of the test I register the models or other factories the same way I do in an initializer by manually registering them as needed for the unit tests.

**Comment by Turbo87** [comment]
@oliverbarnes can you provide a repository that reproduces this issue? otherwise this will be hard/impossible to fix

**Comment by pixelhandler** [comment]
@Turbo87 This is also old I don't think @oliverbarnes has this issue anymore.

**Comment by Turbo87** [comment]
okay, I'll close this for now. if this is indeed still an issue feel free to reopen.
