### ISSUE TITLE
[Question] Using a globals release of ember-mocha is it necessary to setResolver?

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/ember-mocha#52]
Question: If I were using ember-cli I would need to use the resolver from ember-cli/test/helpers/resolver like so:

``` javascript
import resolver from './helpers/resolver';
import { setResolver } from 'ember-mocha';

setResolver(resolver);
```

But If I'm using a globals release of ember-mocha say for rails + ember using Konacha do I even need to set a resolver using ember-mocha `setResolver`?

related docs: http://guides.emberjs.com/v1.10.0/testing/unit-test-helpers/

**Comment by Turbo87** [comment]
@pixelhandler did you figure this out? are you still using `ember-mocha` without Ember CLI?

**Comment by pixelhandler** [comment]
@Turbo87 I'll close this it's old.
