### ISSUE TITLE
Does ember-mocha provide blueprints for ember-cli

### ISSUE THREAD

**Issue by jbryson3** [emberjs/ember-mocha#523]
I'm transitioning from ember-cli-mocha to ember-mocha, and now I'm manually updating my blueprints to be compliant with the latest ember-mocha. Should I expect that `ember-mocha` provides its own blueprints for `ember generate`?

**Comment by Turbo87** [comment]
I assume you're talking about the blueprints for the test files? Those are maintained in the ember-source project itself and have supported ember-mocha for quite some time. (see https://github.com/emberjs/ember.js/blob/7e09bb2ce2d8a5b1b9ace1b07782bbade039587d/blueprints/test-framework-detector.js#L28)
