### ISSUE TITLE
"set" method undefined when using needs

### ISSUE THREAD

**Issue by kswilster** [emberjs/ember-mocha#61]
The `set` method on a test case is `undefined` when using needs. this simple test case passes when the need for the store is removed. `this.subject` and `this.render` still function in the scope of the test case

Test case:

``` js
import { expect } from 'chai';
import { describeComponent, it } from 'ember-mocha';
import hbs from 'htmlbars-inline-precompile';

describeComponent(
    'my-component',
    'Integration: MyComponent',
    {
      integration: true,
      needs: ['store']
    },
    function() {
      it('renders', function() {
        this.set('model', {});
        this.render( hbs`{{my-component model=model}}`);
        expect(this.$('.my-component')).not.to.be.empty;
      });
    }
);
```

Results:

```
Integration: MyComponent renders
    ✘ 'undefined' is not a function (evaluating 'this.set('model', {})')
        TypeError: 'undefined' is not a function (evaluating 'this.set('model', {})')
```

**Comment by ivanvanderbyl** [comment]
Did you ever get this working @kswilster ? I've got the same issue.

**Comment by Fryie** [comment]
I had the same problem, but turns out I was just using an outdated version of ember-mocha, so upgrading should help.

**Comment by Turbo87** [comment]
as @Fryie mentions this should be fixed the recent releases. please reopen if this is indeed still an issue!
