### ISSUE TITLE
Can't run acceptance tests

### ISSUE THREAD

**Issue by rupurt** [emberjs/ember-mocha#64]
Howdy @mattmcmanus & @rwjblue,

We've managed to get ember-mocha working nicely for our unit tests but have had no such luck on the acceptance tests :frowning: 

We get the following error

```
Error: Could not find module `ember/load-initializers` imported from `my-cool-app/app`
```

For this basic test

``` javascript
/* jshint expr:true */
import {
  describe,
  it,
  beforeEach,
  afterEach
} from 'mocha';
import { expect } from 'chai';
import Ember from 'ember';
import startApp from '../helpers/start-app';

describe('Acceptance: Foo', function() {
  var application;

  beforeEach(function() {
    application = startApp();
  });

  afterEach(function() {
    Ember.run(application, 'destroy');
  });

  it('can visit /foo', function() {
    visit('/foo');

    andThen(function() {
      expect(currentPath()).to.equal('foo');
    });
  });
});
```

Are acceptance tests supported and if not, do you have any suggestions for where we to start if we wanted to add support?

**Comment by Robdel12** [comment]
Is there a place you could isolate this error? I'd like to see the stack of the error. There's something else going on here.

**Comment by Turbo87** [comment]
@rupurt can you provide a repository that reproduces this issue? otherwise this will be hard/impossible to fix

**Comment by Turbo87** [comment]
@rupurt it sounds like you're missing the https://github.com/ember-cli/ember-load-initializers addon. please reopen if this is still an issue.
