### ISSUE TITLE
Trouble with visit + andThen in acceptance

### ISSUE THREAD

**Issue by JakeDluhy** [emberjs/ember-mocha#77]
I'm trying to write an acceptance test for my index route, but it keeps failing on the most basic of functions.

``` javascript
describe('with feed items', function() {
  beforeEach(function() {
    // this.feedItems = server.createList('activity', 10, { verb: 'start discussion' });
    this.users = server.createList('user', 5);
    server.createList('group', 5);
    server.createList('group-category', 5);
    server.createList('base-forum', 5);
    this.topics = server.createList('topic', 5);
    this.post = server.createList('post', 5);

    server.create('group', { id: 26, name: 'Snap!' });
    server.createList('topic', 5, { groupId: 26 });

    server.create('question');
    server.createList('question-choice', 4);
    server.createList('question-user-stat', 1);

    server.createList('curated-item', 3);
  });

  it('has the correct path', function() {
    visit('/');
    andThen(() => {
      expect(currentPath()).to.equal('index');
    });
  });
});
```

Gives me the error `TypeError: currentPath is not a function`. However, it gives it to me as an error in the "after each" hook. The error for the test is that the timeout of Xms has exceeded (I've tried 2k, 5k, 10k). Additionally, when I replace currentPath() with 'index' (should easily pass) I get `TypeError: app.testHelpers.wait is not a function`. And finally, when I add a console.log statement within the andThen, it doesn't fire until after the test is over. This all leads me to believe it's a problem with andThen. And thoughts or insights? Thanks!

**Comment by Dhaulagiri** [comment]
@JakeDluhy in my experience things like this have been because of something not being stubbed or created properly in mirage, causing weird side effect errors like the one you are seeing.

**Comment by Turbo87** [comment]
@JakeDluhy do you have a repository somewhere that we can clone to reproduce this? otherwise we can't really help here since this seems to work fine in a few of my projects.

**Comment by JakeDluhy** [comment]
I don't. I've changed jobs and so no longer have access to this repo. I do believe that I had done a small amount of experimentation and determined that it was something else within my repo messing with it. I can't remember any more than that unfortunately. I think this can be closed out. Thanks for the help!
