### ISSUE TITLE
Update "Mocha" for Bower builds

### ISSUE THREAD

**Issue by jbryson3** [emberjs/ember-mocha#78]
I'd like to use the latest mocha in my project. It seems like the latest commit ( https://github.com/switchfly/ember-mocha/commit/e570882cca9cf0ed40e276016f27f1e96c00513e ) would fix that, but doesn't seemed to be pushed to bower.

**Comment by NullVoxPopuli** [comment]
I would also like this. I'd like to use mocha 2.4.5

**Comment by yads** [comment]
That commit won't fix that as it just changes the dev dependencies of the ember-mocha project. [This](https://github.com/switchfly/ember-mocha/blob/master/build-support/bower.json) file needs to be updated. Or if you installed this via [ember-cli-mocha](https://github.com/switchfly/ember-cli-mocha), [this](https://github.com/switchfly/ember-cli-mocha/blob/master/blueprints/ember-cli-mocha/index.js) is the file that needs to be updated.

However, there is nothing stopping you from updating your own bower.json to have the latest mocha build.

**Comment by Turbo87** [comment]
Indeed, what needs to change is https://github.com/emberjs/ember-mocha-builds/blob/master/bower.json#L11 which is copied over from https://github.com/emberjs/ember-mocha/blob/master/build-support/bower.json#L11.
