### ISSUE TITLE
Test helpers not injected into `before`

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember-mocha#81]
In many cases I'd like to use `before` in a nested `describe` or `context` block but test helpers such as `visit` are not defined.

``` js
beforeEach(function() {
  visit("/"); // works fine
});

before(function() {
  visit("/"); // visit is not defined  
});
```

Related:
- https://github.com/samselikoff/ember-cli-mirage/issues/646
- https://github.com/san650/ember-cli-page-object/issues/216

**Comment by Turbo87** [comment]
This is a known "limitation" of Mocha, or rather: that's how Mocha was designed to work. For more details see https://github.com/san650/ember-cli-page-object/issues/216#issuecomment-261339481.
