### ISSUE TITLE
Release instructions aka. "ember-mocha-builds" repository needs an update

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-mocha#95]
It seems that the https://github.com/emberjs/ember-mocha-builds repository wasn't updated for the latest releases of this project.

Are people still using that at all? Do we have to support it forever?

/cc @dgeb @rwjblue

**Comment by rwjblue** [comment]
We probably do not have to support it forever, but it is super convenient to be able to mock up an ember-twiddle.com or jsbin.com to demo a problem (this is the main reason I have kept the ember-qunit-builds one around).

Examples:

* ember-qunit: http://jsbin.com/mocequ/edit?html,js,output
* ember-mocha: http://emberjs.jsbin.com/genolo/edit?html,js,output

**Comment by Turbo87** [comment]
I've merged the diverged branches in the builds repo. `master` should include all current releases again now.
